<a href="https://colab.research.google.com/github/Tclack88/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/module2-loadingdata/LS_DS_112_Loading_Data_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practice Loading Datasets

This assignment is purposely semi-open-ended you will be asked to load datasets both from github and also from CSV files from the [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php). 

Remember that the UCI datasets may not have a file type of `.csv` so it's important that you learn as much as you can about the dataset before you try and load it. See if you can look at the raw text of the file either locally, on github, using the `!curl` shell command, or in some other way before you try and read it in as a dataframe, this will help you catch what would otherwise be unforseen problems.

## 1) Load a dataset from Github (via its *RAW* URL)

Pick a dataset from the following repository and load it into Google Colab. Make sure that the headers are what you would expect and check to see if missing values have been encoded as NaN values:

<https://github.com/ryanleeallred/datasets>

In [0]:
# inspect the data beforehand
!curl https://raw.githubusercontent.com/ryanleeallred/datasets/master/adult.csv

In [0]:
import pandas as pd
import numpy as np
adults = pd.read_csv("https://raw.githubusercontent.com/ryanleeallred/datasets/master/adult.csv",skipinitialspace=True,na_values='?') 
#using 'skipinitialspace=True' is a workaround to the ", " detriment of the dataset

In [57]:
# Verify each '?' in the original data set has been changed to NaN
adults.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
country            583
salary               0
dtype: int64

In [56]:
adults.head(20)

    age         workclass  fnlwgt  ... hours-per-week        country salary
0    39         State-gov   77516  ...             40  United-States  <=50K
1    50  Self-emp-not-inc   83311  ...             13  United-States  <=50K
2    38           Private  215646  ...             40  United-States  <=50K
3    53           Private  234721  ...             40  United-States  <=50K
4    28           Private  338409  ...             40           Cuba  <=50K
5    37           Private  284582  ...             40  United-States  <=50K
6    49           Private  160187  ...             16        Jamaica  <=50K
7    52  Self-emp-not-inc  209642  ...             45  United-States   >50K
8    31           Private   45781  ...             50  United-States   >50K
9    42           Private  159449  ...             40  United-States   >50K
10   37           Private  280464  ...             80  United-States   >50K
11   30         State-gov  141297  ...             40          India   >50K
12   23           Private  122272  ...             30  United-States  <=50K
13   32           Private  205019  ...             50  United-States  <=50K
14   40           Private  121772  ...             40            NaN   >50K
15   34           Private  245487  ...             45         Mexico  <=50K
16   25  Self-emp-not-inc  176756  ...             35  United-States  <=50K
17   32           Private  186824  ...             40  United-States  <=50K
18   38           Private   28887  ...             50  United-States  <=50K
19   43  Self-emp-not-inc  292175  ...             45  United-States   >50K

[20 rows x 15 columns]

## 2) Load a dataset from your local machine
Download a dataset from the [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php) and then upload the file to Google Colab either using the files tab in the left-hand sidebar or by importing `files` from `google.colab` The following link will be a useful resource if you can't remember the syntax: <https://towardsdatascience.com/3-ways-to-load-csv-files-into-colab-7c14fcbdcb92>

While you are free to try and load any dataset from the UCI repository, I strongly suggest starting with one of the most popular datasets like those that are featured on the right-hand side of the home page. 

Some datasets on UCI will have challenges associated with importing them far beyond what we have exposed you to in class today, so if you run into a dataset that you don't know how to deal with, struggle with it for a little bit, but ultimately feel free to simply choose a different one. 

- Make sure that your file has correct headers, and the same number of rows and columns as is specified on the UCI page. If your dataset doesn't have headers use the parameters of the `read_csv` function to add them. Likewise make sure that missing values are encoded as `NaN`.

In [62]:
from google.colab import files
uploaded = files.upload()

Saving Sydney_Data.csv to Sydney_Data.csv

In [101]:
#confirm file is present and see it's size
!ls -hl
# NOTE: The same data set is used in part 3, see there for how I deal with header and missing values

total 86M
drwxr-xr-x 1 root root 4.0K Aug 27 16:17 sample_data
-rw-r--r-- 1 root root  30M Sep  3 21:23 Sydney_Data.csv
drwxr-xr-x 2 root root 4.0K Sep  3 21:42 WECs_DataSet
-rw-r--r-- 1 root root  56M Jul 17 22:12 WECs_DataSet.zip

## 3) Load a dataset from UCI using `!wget`

"Shell Out" and try loading a file directly into your google colab's memory using the `!wget` command and then read it in with `read_csv`.

With this file we'll do a bit more to it.

- Read it in, fix any problems with the header as make sure missing values are encoded as `NaN`.
- Use the `.fillna()` method to fill any missing values. 
 - [.fillna() documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html)
- Create one of each of the following plots using the Pandas plotting functionality:
 - Scatterplot
 - Histogram
 - Density Plot

In [68]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00494/WECs_DataSet.zip

--2019-09-03 21:26:08--  https://archive.ics.uci.edu/ml/machine-learning-databases/00494/WECs_DataSet.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58633205 (56M) [application/x-httpd-php]
Saving to: ‘WECs_DataSet.zip’

WECs_DataSet.zip    100%[===================>]  55.92M  69.3MB/s    in 0.8s

2019-09-03 21:26:09 (69.3 MB/s) - ‘WECs_DataSet.zip’ saved [58633205/58633205]

In [79]:
# The particular data set I acquired was in a a zip file, so it was necessary
# to unzip it then set the file of interest to one in a lower directory
!unzip WECs_DataSet.zip && ls WECs_DataSet

Archive:  WECs_DataSet.zip
replace WECs_DataSet/Adelaide_Data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: WECs_DataSet/Adelaide_Data.csv
  inflating: WECs_DataSet/Perth_Data.csv
  inflating: WECs_DataSet/Sydney_Data.csv
  inflating: WECs_DataSet/Tasmania_Data.csv
Adelaide_Data.csv  Perth_Data.csv  Sydney_Data.csv  Tasmania_Data.csv

In [100]:
sydney_data = pd.read_csv("WECs_DataSet/Sydney_Data.csv", header=None, na_values = '0')
sydney_data.fillna(sydney_data.mean(),inplace=True)
sydney_data.head(50)
# column nan's are filled with the mean of that column
# disclosure: I don't know what this data fully represents, so this may be
# naive on my part

            0           1           2   ...           46           47           48
0   127.943900  264.965600   68.348100  ...  103129.6938   97196.8128  1463622.174
1   500.467700  278.649700   47.406200  ...   94499.4790   88941.7152  1489888.502
2   511.751000  104.438300  566.000000  ...  100646.9126   83394.8729  1495035.934
3    19.699000  216.437800  355.296000  ...   96503.3818   77942.2947  1459841.498
4   344.494077  344.175021  243.342000  ...   94546.5417   85021.1027  1475765.923
5   446.661100  421.036600  493.189500  ...   85799.2132   88227.3054  1486388.580
6   398.066200  344.175021  172.950000  ...   96138.3138   85804.8939  1483891.978
7   113.728600  341.241500  418.005900  ...   93486.0155   90452.2884  1502682.470
8   344.494077  344.175021  279.692061  ...   99725.2615   81533.2130  1477945.897
9   369.207100  304.051500  566.000000  ...   98025.2705   97873.2116  1476718.888
10   39.847800  231.841100  176.477800  ...   96622.4424   92283.2428  1504052.297
11  439.035800  344.175021  351.070600  ...   95019.6368   97485.6874  1477597.900
12   50.098600  158.514300  279.692061  ...   96508.4990   79568.9879  1452738.179
13  272.500400   58.267900  517.656100  ...   78237.8073  106174.4380  1469950.155
14  413.798800  303.920200   22.498800  ...   82255.4552   92050.8420  1469004.895
15  566.000000  344.175021  543.338100  ...   84858.4997   96252.5069  1484326.398
16   97.918400  232.250500  437.753700  ...   97586.9676   86696.3921  1469960.177
17  566.000000   46.262500  566.000000  ...   80796.1302   96413.1221  1475498.309
18  221.717200  344.175021  266.141100  ...   82771.0387   93959.4097  1463385.200
19  566.000000    1.808200  449.670200  ...   87275.4101   89331.9337  1450994.427
20  566.000000  215.393900  190.137100  ...   84958.4705   88501.2513  1469187.802
21  452.958700  141.119200  161.105500  ...   80554.8201   86723.2703  1433958.695
22  467.557000  164.129700  490.425800  ...   91123.2390   80607.6818  1463515.593
23  515.932800  176.350400  259.560900  ...   86086.2139   88639.1390  1481123.053
24  343.626000   84.965200  142.156100  ...   92277.5862   87459.4654  1473786.975
25  566.000000  227.317800  134.961400  ...   95262.3019   84267.0588  1470135.303
26  424.047100  165.471200   96.484900  ...   85241.9667   94914.7894  1440645.643
27  525.451900  224.151500  435.761600  ...   92561.3517   86716.0643  1484064.908
28  565.808600  301.103700  178.298600  ...   93522.8990   79381.0553  1465186.987
29  559.470800  308.095700    5.183900  ...   86694.0319   87829.1008  1476189.410
30  566.000000  425.055600  213.556700  ...   82461.1195   90677.8083  1462683.795
31  566.000000  380.526000  279.692061  ...   91702.8640   87949.5973  1496286.307
32  566.000000  316.623100  279.692061  ...   91046.0091   89510.0297  1489959.409
33  566.000000  352.733800  279.692061  ...   83104.6127   88743.5733  1485734.661
34  501.029000  350.132500  211.276000  ...   98203.9824   83222.4651  1483709.227
35  372.229200  268.732200  279.692061  ...   86610.0575   89636.7087  1491886.420
36  367.472600  191.211700  279.692061  ...   82252.0034   93570.5102  1465462.500
37  389.208500  405.374400  279.692061  ...   92949.8939   91135.4487  1495179.053
38  516.048100  333.335200  279.692061  ...   90841.0459   87981.9993  1492402.895
39  493.476600  290.948500  279.692061  ...   82823.2919   89967.2029  1486117.326
40  463.038900  299.207000   96.221800  ...   91721.2485   87264.5575  1492748.464
41  477.295400  287.149500  176.289700  ...   93146.3320   85911.9788  1478822.920
42  566.000000  397.137600   60.188900  ...   88753.9694   88868.4371  1479099.448
43  519.993400  225.914800  279.692061  ...   86974.7350   89725.7709  1480583.999
44  487.890500  205.407900   39.945400  ...   89772.5125   91835.7945  1502075.176
45  543.409600  326.108800   72.333600  ...   90953.3564   90869.1380  1495309.571
46  446.106400  383.637100    2.707600  ...   90187.4858   86968.2079  1496628.185
47  526.212000  360.838600  114.944200  ...   85951.6837   93058.5120  1481778.349
48  566.000000  335.769800   36.598500  ...   83767.9402   86852.6403  1489704.050
49  480.835200  259.824600  279.692061  ...   89488.0568   88937.8743  1505582.584

[50 rows x 49 columns]

## Stretch Goals - Other types and sources of data

Not all data comes in a nice single file - for example, image classification involves handling lots of image files. You still will probably want labels for them, so you may have tabular data in addition to the image blobs - and the images may be reduced in resolution and even fit in a regular csv as a bunch of numbers.

If you're interested in natural language processing and analyzing text, that is another example where, while it can be put in a csv, you may end up loading much larger raw data and generating features that can then be thought of in a more standard tabular fashion.

Overall you will in the course of learning data science deal with loading data in a variety of ways. Another common way to get data is from a database - most modern applications are backed by one or more databases, which you can query to get data to analyze. We'll cover this more in our data engineering unit.

How does data get in the database? Most applications generate logs - text files with lots and lots of records of each use of the application. Databases are often populated based on these files, but in some situations you may directly analyze log files. The usual way to do this is with command line (Unix) tools - command lines are intimidating, so don't expect to learn them all at once, but depending on your interests it can be useful to practice.

One last major source of data is APIs: https://github.com/toddmotto/public-apis

API stands for Application Programming Interface, and while originally meant e.g. the way an application interfaced with the GUI or other aspects of an operating system, now it largely refers to online services that let you query and retrieve data. You can essentially think of most of them as "somebody else's database" - you have (usually limited) access.

*Stretch goal* - research one of the above extended forms of data/data loading. See if you can get a basic example working in a notebook. Image, text, or (public) APIs are probably more tractable - databases are interesting, but there aren't many publicly accessible and they require a great deal of setup.

In [106]:
# This is cheating because this 'example' was already given in the webpage
!curl -X GET https://api.carbonintensity.org.uk/intensity \
  -H 'Accept: application/json'

{
  "data":[{
    "from": "2019-09-03T22:00Z",
    "to": "2019-09-03T22:30Z",
    "intensity": {
      "forecast": 147,
      "actual": 126,
      "index": "low"
    }
  }]
}